[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/bot"]

[workspace.dependencies]
aaf_shared = { path = "crates/shared" }
asahi = { git = "https://git.playground.red/nwerosama/asahi", branch = "master", features = ["prober", "coordinator", "sqlx-pg"] }
farmsim = { version = "0.2.2", features = ["fs22", "fs25"] }
num-format = "0.4.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.52.1", features = ["rt-multi-thread", "macros", "signal"] }

[profile]
dev.opt-level = 0
release.opt-level = 2
