[package]
name = "aafbot"
version = "0.1.4"
edition = "2024"

[dependencies]
asahi = { git = "https://git.playground.red/nwerosama/asahi", branch = "master", features = ["prober", "sqlx-pg"] }
poise = { git = "https://git.playground.red/nwerosama/poise", branch = "lock-serenity-commit" }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "signal"] }

[[bin]]
name = "aaf"
path = "src/main.rs"

[features]
production = []

[profile]
dev.opt-level = 0
release.opt-level = 2
