apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-app

spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: aaf-app
  template:
    metadata:
      labels:
        app: aaf-app
    spec:
      serviceAccountName: aaf-serviceaccount
      imagePullSecrets:
        - name: regcred
      containers:
        - name: aaf-app
          image: ghcr.io/nwerosama/aafbot:sanke
          imagePullPolicy: Always
          env:
            - name: NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name: aaf-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 9100
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9100
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "32Mi"
            limits:
              cpu: "1200m"
              memory: "128Mi"
        - name: aaf-vpn
          image: ghcr.io/tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
            - name: TS_KUBE_SECRET
              value: tailscale-secret
            - name: TS_USERSPACE
              value: "false"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          envFrom:
            - secretRef:
                name: tailscale-secret
          resources:
            requests:
              cpu: "500m"
              memory: "16Mi"
            limits:
              cpu: "1800m"
              memory: "64Mi"
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: aafbot-service

spec:
  selector:
    app: aaf-app
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      name: health
