CREATE TABLE IF NOT EXISTS servers (
  friendly VARCHAR(30) NOT NULL PRIMARY KEY,
  internal VARCHAR(30) NOT NULL UNIQUE,
  ip VARCHAR(21) NOT NULL,
  code VARCHAR(32) NOT NULL
);

ALTER TABLE servers ADD COLUMN IF NOT EXISTS game_version SMALLINT;
